### ISSUE TITLE
Project description is behind a paywall

### ISSUE THREAD

**Issue by iljya** [romanorac/pandas-analytics-server#1]
I tried to find out more about the project from the linked article:
https://towardsdatascience.com/pandas-analytics-server-d9abceec888b

But, regrettably, it is behind a paywall.

**Comment by romanorac** [comment]
Can you send me the link which is behind the paywall

**Comment by iljya** [comment]
it's the link included above (Medium has a pay wall). Here is what I see:

"How to read this story — and everything else on Medium.
Not every story on Medium is free, like this one. Become a member to get unlimited access and support the voices you want to hear more from."

**Comment by romanorac** [comment]
Just open the story in an incognito window with Chrome 😉

**Comment by tomron** [comment]
This is what I get when clicking the link - 
<img width="953" alt="Screen Shot 2020-11-22 at 8 22 46" src="https://user-images.githubusercontent.com/5007372/99896717-e9dc1600-2c9b-11eb-9270-3aaf421a3cc7.png">

**Comment by romanorac** [comment]
I've updated the link. It should work without incognito mode.
